INSERT INTO Sacher_ambito(nome, progetto_id, colore_id, padre_id)
VALUES('Cantiere',%(bc_id)s,1,null),
('Cantiere di restauro',%(bc_id)s,null,%(id_1)s),
('Dati amministrativi',%(bc_id)s,null,%(id_2)s),
('Organigramma',%(bc_id)s,null,%(id_3)s),
('Personale',%(bc_id)s,null,%(id_3)s),
('Autorizzazioni',%(bc_id)s,null,%(id_3)s),
('Sicurezza',%(bc_id)s,null,%(id_3)s),
('Contabilità',%(bc_id)s,null,%(id_3)s),
('Gestione qualità',%(bc_id)s,null,%(id_2)s),
('Giornale di cantiere',%(bc_id)s,null,%(id_2)s),
('Schede tecniche',%(bc_id)s,null,%(id_2)s),
('Attrezzature',%(bc_id)s,null,%(id_11)s),
('Materiali',%(bc_id)s,null,%(id_11)s),
('Dati descrittivi',%(bc_id)s,2,null),
('Storia dell\'edificio',%(bc_id)s,null,%(id_14)s),
('Notizie storico critiche',%(bc_id)s,null,%(id_15)s),
('Evoluzione architettonica',%(bc_id)s,null,%(id_15)s),
('Storia dei restauri',%(bc_id)s,null,%(id_14)s),
('Documentazione multimediale',%(bc_id)s,null,%(id_14)s),
('Fotografica',%(bc_id)s,null,%(id_19)s),
('Generale',%(bc_id)s,null,%(id_20)s),
('Di dettaglio',%(bc_id)s,null,%(id_20)s),
('Storica',%(bc_id)s,null,%(id_20)s),
('Testuale',%(bc_id)s,null,%(id_19)s),
('Fonti',%(bc_id)s,null,%(id_24)s),
('Archivistiche',%(bc_id)s,null,%(id_25)s),
('Bibliografiche',%(bc_id)s,null,%(id_25)s),
('Relazione',%(bc_id)s,null,%(id_24)s),
('Grafica',%(bc_id)s,null,%(id_19)s),
('Raster',%(bc_id)s,null,%(id_29)s),
('Vettoriale',%(bc_id)s,null,%(id_29)s),
('Tridimensionale',%(bc_id)s,null,%(id_19)s),
('Nuvola di punti',%(bc_id)s,null,%(id_32)s),
('Mesh poligonale',%(bc_id)s,null,%(id_32)s),
('Audio',%(bc_id)s,null,%(id_19)s),
('Video',%(bc_id)s,null,%(id_19)s),
('Materiali costitutivi',%(bc_id)s,null,%(id_14)s),
('Materiali lapidei',%(bc_id)s,null,%(id_37)s),
('Arenaria',%(bc_id)s,null,%(id_38)s),
('Materiali lignei',%(bc_id)s,null,%(id_37)s),
('Materiali metallici',%(bc_id)s,null,%(id_37)s),
('Ferroso',%(bc_id)s,null,%(id_41)s),
('Ferro',%(bc_id)s,null,%(id_42)s),
('Non-ferroso',%(bc_id)s,null,%(id_41)s),
('Lega metallica',%(bc_id)s,null,%(id_41)s),
('Bronzo',%(bc_id)s,null,%(id_45)s),
('Materiali ceramici',%(bc_id)s,null,%(id_37)s),
('Materiali vetrosi',%(bc_id)s,null,%(id_47)s),
('Laterizio',%(bc_id)s,null,%(id_47)s),
('Materiale compositi',%(bc_id)s,null,%(id_37)s),
('Conglomerati cementizi',%(bc_id)s,null,%(id_50)s),
('Malta',%(bc_id)s,null,%(id_51)s),
('Calcestruzzo',%(bc_id)s,null,%(id_51)s),
('Intonaco',%(bc_id)s,null,%(id_51)s),
('Materiali polimerici',%(bc_id)s,null,%(id_37)s),
('Multimateriale',%(bc_id)s,null,%(id_37)s),
('Tecniche esecutive/segni di lavorazione',%(bc_id)s,null,%(id_14)s),
('Agemina',%(bc_id)s,null,%(id_57)s),
('Incisione',%(bc_id)s,null,%(id_57)s),
('Pietra intagliata',%(bc_id)s,null,%(id_57)s),
('Pietra scolpita',%(bc_id)s,null,%(id_57)s),
('Gradina',%(bc_id)s,null,%(id_57)s),
('Raspa',%(bc_id)s,null,%(id_57)s),
('Scalpello',%(bc_id)s,null,%(id_57)s),
('Subbia',%(bc_id)s,null,%(id_57)s),
('Tecniche costruttive',%(bc_id)s,null,%(id_14)s),
('Muratura',%(bc_id)s,null,%(id_66)s),
('In laterizio',%(bc_id)s,null,%(id_67)s),
('In pietra',%(bc_id)s,null,%(id_67)s),
('Mista',%(bc_id)s,null,%(id_67)s),
('Diagnostica',%(bc_id)s,3,null),
('Alterazione/degrado',%(bc_id)s,null,%(id_71)s),
('Stato di conservazione',%(bc_id)s,null,%(id_72)s),
('Abrasione',%(bc_id)s,null,%(id_73)s),
('Alveolizzazione',%(bc_id)s,null,%(id_73)s),
('Alterazione cromatica',%(bc_id)s,null,%(id_73)s),
('Colatura',%(bc_id)s,null,%(id_73)s),
('Colonizzazione biologica',%(bc_id)s,null,%(id_73)s),
('Corrosione',%(bc_id)s,null,%(id_73)s),
('Cricche',%(bc_id)s,null,%(id_73)s),
('Crosta',%(bc_id)s,null,%(id_73)s),
('Danno di tipo antropico',%(bc_id)s,null,%(id_73)s),
('Deformazione',%(bc_id)s,null,%(id_73)s),
('Degradazione differenziale',%(bc_id)s,null,%(id_73)s),
('Deiezioni animali',%(bc_id)s,null,%(id_73)s),
('Deposito',%(bc_id)s,null,%(id_73)s),
('Disgregazione',%(bc_id)s,null,%(id_73)s),
('Distacco',%(bc_id)s,null,%(id_73)s),
('Efflorescenza',%(bc_id)s,null,%(id_73)s),
('Erosione',%(bc_id)s,null,%(id_73)s),
('Esfoliazione',%(bc_id)s,null,%(id_73)s),
('Fessura, frattura',%(bc_id)s,null,%(id_73)s),
('Fronte di risalita',%(bc_id)s,null,%(id_73)s),
('Geodetica',%(bc_id)s,null,%(id_73)s),
('Graffito vandalico',%(bc_id)s,null,%(id_73)s),
('Incrostazione',%(bc_id)s,null,%(id_73)s),
('Lacuna',%(bc_id)s,null,%(id_73)s),
('Lamina di rattoppo',%(bc_id)s,null,%(id_73)s),
('Macchia',%(bc_id)s,null,%(id_73)s),
('Mancanza',%(bc_id)s,null,%(id_73)s),
('Ossidazione',%(bc_id)s,null,%(id_73)s),
('Patina',%(bc_id)s,null,%(id_73)s),
('Pellicola',%(bc_id)s,null,%(id_73)s),
('Perdita di vincolo',%(bc_id)s,null,%(id_73)s),
('Pitting',%(bc_id)s,null,%(id_73)s),
('Polverizzazione',%(bc_id)s,null,%(id_73)s),
('Fessurazione, fratturazione',%(bc_id)s,null,%(id_73)s),
('Porosità',%(bc_id)s,null,%(id_73)s),
('Presenza di vegetazione',%(bc_id)s,null,%(id_73)s),
('Prodotti di corrosione',%(bc_id)s,null,%(id_73)s),
('Sbollitura, spugnosità',%(bc_id)s,null,%(id_73)s),
('Scagliatura',%(bc_id)s,null,%(id_73)s),
('Scritte vandaliche',%(bc_id)s,null,%(id_73)s),
('Sostanze grasse',%(bc_id)s,null,%(id_73)s),
('Taglio',%(bc_id)s,null,%(id_73)s),
('Consolidamento',%(bc_id)s,null,%(id_73)s),
('Foro',%(bc_id)s,null,%(id_73)s),
('Grappe',%(bc_id)s,null,%(id_73)s),
('Incisione',%(bc_id)s,null,%(id_73)s),
('Incollaggi',%(bc_id)s,null,%(id_73)s),
('Integrazione',%(bc_id)s,null,%(id_73)s),
('Patinatura',%(bc_id)s,null,%(id_73)s),
('Perni',%(bc_id)s,null,%(id_73)s),
('Protezione superficiale',%(bc_id)s,null,%(id_73)s),
('Riempimento',%(bc_id)s,null,%(id_73)s),
('Rilavorazioni',%(bc_id)s,null,%(id_73)s),
('Saldatura, incollaggio',%(bc_id)s,null,%(id_73)s),
('Sistema antipiccione',%(bc_id)s,null,%(id_73)s),
('Stuccatura',%(bc_id)s,null,%(id_73)s),
('Tasselli',%(bc_id)s,null,%(id_73)s),
('Verniciatura',%(bc_id)s,null,%(id_73)s),
('Condizioni ambientali',%(bc_id)s,null,%(id_71)s),
('Analisi strumentali',%(bc_id)s,null,%(id_71)s),
('Distruttive/microdistruttive',%(bc_id)s,null,%(id_133)s),
('Analisi mineralogico-petrografiche',%(bc_id)s,null,%(id_134)s),
('Analisi microstratigrafiche',%(bc_id)s,null,%(id_134)s),
('X-grafia',%(bc_id)s,null,%(id_134)s),
('Carotaggio',%(bc_id)s,null,%(id_134)s),
('Saggio stratigrafico',%(bc_id)s,null,%(id_134)s),
('Non distruttive',%(bc_id)s,null,%(id_133)s),
('Analisi sprettroscopica/spettrometrica',%(bc_id)s,null,%(id_140)s),
('Imaging multispettrale',%(bc_id)s,null,%(id_140)s),
('Termografia',%(bc_id)s,null,%(id_140)s),
('Georadar',%(bc_id)s,null,%(id_140)s),
('Analisi sonica',%(bc_id)s,null,%(id_140)s),
('Analisi al microscopio',%(bc_id)s,null,%(id_140)s),
('Ottico',%(bc_id)s,null,%(id_146)s),
('Elettronico',%(bc_id)s,null,%(id_146)s),
('Analisi diffrattometrica',%(bc_id)s,null,%(id_140)s),
('Videoendoscopia',%(bc_id)s,null,%(id_140)s),
('Test',%(bc_id)s,null,%(id_140)s),
('Analisi dei sali solubili',%(bc_id)s,null,%(id_140)s),
('Analisi fisiche',%(bc_id)s,null,%(id_140)s),
('Analisi chimiche',%(bc_id)s,null,%(id_140)s),
('Analisi biologiche colturali',%(bc_id)s,null,%(id_140)s),
('Altro',%(bc_id)s,null,%(id_140)s),
('Progetto',%(bc_id)s,4,null),
('Progetto di restauro',%(bc_id)s,null,%(id_157)s),
('Conservativo',%(bc_id)s,null,%(id_158)s),
('Strutturale',%(bc_id)s,null,%(id_158)s),
('Progetto di ricerca',%(bc_id)s,null,%(id_157)s),
('Intervento',%(bc_id)s,5,null),
('Messa in sicurezza',%(bc_id)s,null,%(id_162)s),
('Interventi di messa in sicurezza',%(bc_id)s,null,%(id_163)s),
('Intervento di restauro',%(bc_id)s,null,%(id_162)s),
('Interventi di conservazione e restauro',%(bc_id)s,null,%(id_165)s),
('Convertitore di corrosione',%(bc_id)s,null,%(id_166)s),
('Equilibratura cromatica',%(bc_id)s,null,%(id_166)s),
('Estrazione sali solubili',%(bc_id)s,null,%(id_166)s),
('Incollaggio',%(bc_id)s,null,%(id_166)s),
('Inibitore di corrosione',%(bc_id)s,null,%(id_166)s),
('Integrazione',%(bc_id)s,null,%(id_166)s),
('Passivazione della corrosione',%(bc_id)s,null,%(id_166)s),
('Presentazione estetica',%(bc_id)s,null,%(id_166)s),
('Protezione superficiale',%(bc_id)s,null,%(id_166)s),
('Pulitura chimica',%(bc_id)s,null,%(id_166)s),
('Pulitura meccanica',%(bc_id)s,null,%(id_166)s),
('Riassemblaggio frammenti',%(bc_id)s,null,%(id_166)s),
('Rimozione deposito coerente',%(bc_id)s,null,%(id_166)s),
('Rimozione deposito incoerente',%(bc_id)s,null,%(id_166)s),
('Rimozione stuccatura',%(bc_id)s,null,%(id_166)s),
('Sistema antipiccione',%(bc_id)s,null,%(id_166)s),
('Staffa',%(bc_id)s,null,%(id_166)s),
('Stuccatura',%(bc_id)s,null,%(id_166)s),
('Test di pulitura',%(bc_id)s,null,%(id_166)s),
('Trattamento biocida',%(bc_id)s,null,%(id_166)s),
('Manutenzione',%(bc_id)s,6,null),
('Ordinaria',%(bc_id)s,null,%(id_187)s),
('Programmata',%(bc_id)s,null,%(id_187)s),
('Straordinaria',%(bc_id)s,null,%(id_187)s);